# Generated by Django 3.2 on 2023-03-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionmessage',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
